# Generated by Django 5.1.5 on 2025-03-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('AWS', 'AWS'), ('Azure', 'Azure'), ('GCP', 'GCP')], max_length=50)),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField(help_text='API endpoint for fetching instance metrics')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(help_text='CPU usage in percentage')),
                ('memory_usage', models.FloatField(help_text='RAM usage in percentage')),
                ('network_usage', models.FloatField(help_text='Disk usage in percentage')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_data', to='myapps.cloudinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ScalingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scale_up', 'Scale Up'), ('scale_down', 'Scale Down')], max_length=50)),
                ('status', models.CharField(help_text='Status of scaling operation (e.g., Success, Failed)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_actions', to='myapps.cloudinstance')),
            ],
        ),
    ]
