# Generated by Django 5.1.5 on 2025-02-03 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_pipelinestage_script_stage_tool_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='script_link',
            new_name='script',
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('selected_option', models.CharField(choices=[('scripts', 'Scripts'), ('tools', 'Tools')], default='scripts', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapps.script')),
                ('selected_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapps.pipelinestage')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapps.tool')),
            ],
        ),
    ]
