# Generated by Django 5.1.2 on 2025-03-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_cloudinstance_monitoringdata_scalingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringdata',
            name='disk_usage',
            field=models.FloatField(default=0, help_text='Disk usage in percentage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoringdata',
            name='network_usage',
            field=models.FloatField(help_text='Network usage in percentage'),
        ),
    ]
