# Generated by Django 5.1.5 on 2025-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_cloudinstance_monitoringdata_scalingaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(help_text='CPU usage in percentage')),
                ('memory_usage', models.FloatField(help_text='RAM usage in percentage')),
                ('disk_usage', models.FloatField(help_text='Disk usage in percentage')),
                ('network_sent', models.FloatField(help_text='Network sent (MB)')),
                ('network_received', models.FloatField(help_text='Network received (MB)')),
            ],
        ),
        migrations.RenameField(
            model_name='monitoringdata',
            old_name='network_usage',
            new_name='disk_usage',
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='network_received',
            field=models.FloatField(default=0.0, help_text='Network received (MB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='network_sent',
            field=models.FloatField(default=0, help_text='Network sent (MB)'),
            preserve_default=False,
        ),
    ]
