# Generated by Django 5.1.5 on 2025-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_systemusage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringdata',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='monitoringdata',
            name='network_received',
        ),
        migrations.RemoveField(
            model_name='monitoringdata',
            name='network_sent',
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='network_usage',
            field=models.FloatField(default=0, help_text='Network usage in percentage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoringdata',
            name='memory_usage',
            field=models.FloatField(help_text='Memory usage in percentage'),
        ),
        migrations.AlterField(
            model_name='monitoringdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of the data collected'),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='cpu_usage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='disk_usage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='memory_usage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='network_received',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='network_sent',
            field=models.FloatField(),
        ),
    ]
