# Generated by Django 5.1.5 on 2025-02-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_rename_script_link_script_script_projectdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='deployment_type',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='framework',
            field=models.CharField(default='default_framework', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='hosting_platform',
            field=models.CharField(default='default_platform', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='programming_language',
            field=models.CharField(default='default_language', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_type',
            field=models.CharField(default='default_project_type', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='testing_needs',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
