# Generated by Django 5.1.5 on 2025-04-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_remove_monitoringdata_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemusage',
            name='cpu_usage',
            field=models.FloatField(help_text='CPU usage in percentage'),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='disk_usage',
            field=models.FloatField(help_text='Disk usage in percentage'),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='memory_usage',
            field=models.FloatField(help_text='Memory usage in percentage'),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='network_received',
            field=models.FloatField(help_text='Amount of data received (in MB)'),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='network_sent',
            field=models.FloatField(help_text='Amount of data sent (in MB)'),
        ),
        migrations.AlterField(
            model_name='systemusage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the data was recorded'),
        ),
        migrations.CreateModel(
            name='ScalingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_scaling', models.BooleanField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('system_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.systemusage')),
            ],
        ),
    ]
