# Generated by Django 5.1.2 on 2025-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_alter_systemusage_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudinstance',
            name='provider',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Azure', 'Azure')], max_length=50),
        ),
    ]
